import './ProgramManager';
import './changePrompt';
import './exit';
import './skills'
import './hello';
import './help';
import './clear';
import './echo';
import './about';
import './contact';
import './work';
import './man';
import './sandwich';
